In [1]:
'''
first we have to import numpy
'''
import numpy as np


Question 1
---


Write a NumPy program to create an array of all even integers from 30 to 70.

In [2]:
'''
you can use the numpy's function arange
this function takes the parameter start,stop and steps we are going to take
np.arange(start,stop,step,dtype=)
'''

arr=np.arange(30,70,2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

Question 2
---

Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

In [3]:
# the rand function print the values
arr=np.random.rand(15)
print(arr,'\n')

# but the randn function print the values from -1 to +1 in a standard normal distribution e.g: Return a sample (or samples) from the “standard normal” distribution (from documentation)
arr=np.random.randn(15)
print('value range in standard normal distribution:')
print('\n',arr)

[0.70422759 0.12879445 0.18203783 0.63584096 0.20313207 0.52152275
 0.81572828 0.90672632 0.37442052 0.89658608 0.21329347 0.86131829
 0.82183045 0.33543577 0.35113185] 

value range in standard normal distribution:

 [ 0.07747564 -0.90120438  0.75525382 -0.99428206 -0.31713874 -0.15883729
 -0.38021012 -0.42738647  2.76045105 -0.4787903  -0.1380877  -0.53275302
 -0.23600925  0.59855149 -0.7726183 ]


Question 3
---

How to compute the cross-product of two matrices in NumPy?


In [4]:
mat1=np.random.randint(2,7,(3,3))
print('the first matrix is: ',mat1)
mat2=np.random.randint(2,7,(3,3))
print('the second matrix is: ',mat2)
'''
The dot product is the result in a scalar quantity
'''
dot_=np.dot(mat1,mat2)
print('dot product is:')
print(dot_)
print('cross product is:')
dot_=np.cross(mat1,mat2)
print(dot_)
# only difference is that the dot product compute a scalar value while cross product result in a vector

the first matrix is:  [[3 3 2]
 [6 2 3]
 [6 2 3]]
the second matrix is:  [[2 3 6]
 [3 3 2]
 [3 3 3]]
dot product is:
[[21 24 30]
 [27 33 49]
 [27 33 49]]
cross product is:
[[ 12 -14   3]
 [ -5  -3  12]
 [ -3  -9  12]]


Question 4
---


How to compute the determinant of an array using NumPy?

In [5]:
# numpy has a function in its linear algebra module name as det for computing determinant of a matrix

mat1=np.random.randint(3,6,(2,2))
print('determinant of matrix is: ',np.linalg.det(mat1))

determinant of matrix is:  12.999999999999995


Question 5
---


How to create a 3x3x3 array with random values using NumPy?

In [8]:
# use the random module and the randint function for that purpose
arr=np.random.randint(2,8,(3,3,3))
arr

array([[[6, 4, 6],
        [2, 6, 7],
        [4, 7, 3]],

       [[7, 6, 7],
        [7, 4, 4],
        [3, 3, 6]],

       [[7, 3, 6],
        [3, 5, 7],
        [7, 3, 6]]])

Question 6
---


How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?

In [12]:
# create a 5x5 matrix
np.random.seed(42) # to print same values all the time
arr=np.random.randint(0,9,(5,5))
arr

array([[6, 3, 7, 4, 6],
       [2, 6, 7, 4, 3],
       [7, 7, 2, 5, 4],
       [1, 7, 5, 1, 4],
       [0, 5, 8, 0, 2]])

In [13]:
# finding minimum
np.min(arr)

0

In [14]:
# finding maximum
np.max(arr)

8

Question 7
---

How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?


In [16]:
# create an array
arr=np.array([[1,3,2],[7,1,9]])

In [19]:
# compute mean at second axis
# as second axis here is 1
np.mean(arr,axis=1)
# here it is computing the mean of values in the the rows associated with columns

array([2.        , 5.66666667])

In [25]:
# now compute standard deviation
np.std(arr,axis=1)

array([0.81649658, 3.39934634])

In [23]:
# for variance
np.var(arr,axis=1)

array([ 0.66666667, 11.55555556])